
import repositoryReduser, { repositoryRemoved, repositoryEdit, repositorySliceType } from "./repositorySlice";

describe('getCounterValue', () => {
  const testData: repositorySliceType = {
    items: [
      {
        id: 28457823,
        node_id: 'MDEwOlJlcG9zaXRvcnkyODQ1NzgyMw==',
        name: 'freeCodeCamp',
        full_name: 'freeCodeCamp/freeCodeCamp',
        'private': false,
        owner: {
          login: 'freeCodeCamp',
          id: 9892522,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjk4OTI1MjI=',
          avatar_url: 'https://avatars.githubusercontent.com/u/9892522?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/freeCodeCamp',
          html_url: 'https://github.com/freeCodeCamp',
          followers_url: 'https://api.github.com/users/freeCodeCamp/followers',
          following_url: 'https://api.github.com/users/freeCodeCamp/following{/other_user}',
          gists_url: 'https://api.github.com/users/freeCodeCamp/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/freeCodeCamp/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/freeCodeCamp/subscriptions',
          organizations_url: 'https://api.github.com/users/freeCodeCamp/orgs',
          repos_url: 'https://api.github.com/users/freeCodeCamp/repos',
          events_url: 'https://api.github.com/users/freeCodeCamp/events{/privacy}',
          received_events_url: 'https://api.github.com/users/freeCodeCamp/received_events',
          type: 'Organization',
          user_view_type: 'public',
          site_admin: false
        },
        html_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
        description: 'freeCodeCamp.org\'s open-source codebase and curriculum. Learn to code for free.',
        fork: false,
        url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp',
        forks_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/forks',
        keys_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/teams',
        hooks_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/hooks',
        issue_events_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/events{/number}',
        events_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/events',
        assignees_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/assignees{/user}',
        branches_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/branches{/branch}',
        tags_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/tags',
        blobs_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/languages',
        stargazers_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/stargazers',
        contributors_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contributors',
        subscribers_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscribers',
        subscription_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/subscription',
        commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/contents/{+path}',
        compare_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/merges',
        archive_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/downloads',
        issues_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/issues{/number}',
        pulls_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/labels{/name}',
        releases_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/releases{/id}',
        deployments_url: 'https://api.github.com/repos/freeCodeCamp/freeCodeCamp/deployments',
        created_at: '2014-12-24T17:49:19Z',
        updated_at: '2024-10-30T16:17:32Z',
        pushed_at: '2024-10-30T15:34:33Z',
        git_url: 'git://github.com/freeCodeCamp/freeCodeCamp.git',
        ssh_url: 'git@github.com:freeCodeCamp/freeCodeCamp.git',
        clone_url: 'https://github.com/freeCodeCamp/freeCodeCamp.git',
        svn_url: 'https://github.com/freeCodeCamp/freeCodeCamp',
        homepage: 'https://contribute.freecodecamp.org',
        size: 471698,
        stargazers_count: 404771,
        watchers_count: 404771,
        language: 'TypeScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: false,
        has_pages: false,
        has_discussions: false,
        forks_count: 37966,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 232,
        license: {
          key: 'bsd-3-clause',
          name: 'BSD 3-Clause "New" or "Revised" License',
          spdx_id: 'BSD-3-Clause',
          url: 'https://api.github.com/licenses/bsd-3-clause',
          node_id: 'MDc6TGljZW5zZTU='
        },
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [
          'careers',
          'certification',
          'community',
          'curriculum',
          'd3',
          'education',
          'freecodecamp',
          'hacktoberfest',
          'javascript',
          'learn-to-code',
          'math',
          'nodejs',
          'nonprofits',
          'programming',
          'react',
          'teachers'
        ],
        visibility: 'public',
        forks: 37966,
        open_issues: 232,
        watchers: 404771,
        default_branch: 'main',
        score: 1
      },
      {
        id: 10270250,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
        name: 'react',
        full_name: 'facebook/react',
        'private': false,
        owner: {
          login: 'facebook',
          id: 69631,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
          avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/facebook',
          html_url: 'https://github.com/facebook',
          followers_url: 'https://api.github.com/users/facebook/followers',
          following_url: 'https://api.github.com/users/facebook/following{/other_user}',
          gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
          organizations_url: 'https://api.github.com/users/facebook/orgs',
          repos_url: 'https://api.github.com/users/facebook/repos',
          events_url: 'https://api.github.com/users/facebook/events{/privacy}',
          received_events_url: 'https://api.github.com/users/facebook/received_events',
          type: 'Organization',
          user_view_type: 'public',
          site_admin: false
        },
        html_url: 'https://github.com/facebook/react',
        description: 'The library for web and native user interfaces.',
        fork: false,
        url: 'https://api.github.com/repos/facebook/react',
        forks_url: 'https://api.github.com/repos/facebook/react/forks',
        keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/facebook/react/teams',
        hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
        issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
        events_url: 'https://api.github.com/repos/facebook/react/events',
        assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
        branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
        tags_url: 'https://api.github.com/repos/facebook/react/tags',
        blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/facebook/react/languages',
        stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
        contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
        subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
        subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
        commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
        compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/facebook/react/merges',
        archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
        issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
        pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
        releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
        deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
        created_at: '2013-05-24T16:15:54Z',
        updated_at: '2024-10-30T15:55:22Z',
        pushed_at: '2024-10-30T01:51:44Z',
        git_url: 'git://github.com/facebook/react.git',
        ssh_url: 'git@github.com:facebook/react.git',
        clone_url: 'https://github.com/facebook/react.git',
        svn_url: 'https://github.com/facebook/react',
        homepage: 'https://react.dev',
        size: 632802,
        stargazers_count: 228819,
        watchers_count: 228819,
        language: 'JavaScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: true,
        has_discussions: false,
        forks_count: 46825,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 864,
        license: {
          key: 'mit',
          name: 'MIT License',
          spdx_id: 'MIT',
          url: 'https://api.github.com/licenses/mit',
          node_id: 'MDc6TGljZW5zZTEz'
        },
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [
          'declarative',
          'frontend',
          'javascript',
          'library',
          'react',
          'ui'
        ],
        visibility: 'public',
        forks: 46825,
        open_issues: 864,
        watchers: 228819,
        default_branch: 'main',
        score: 1
      },
      {
        id: 11730342,
        node_id: 'MDEwOlJlcG9zaXRvcnkxMTczMDM0Mg==',
        name: 'vue',
        full_name: 'vuejs/vue',
        'private': false,
        owner: {
          login: 'vuejs',
          id: 6128107,
          node_id: 'MDEyOk9yZ2FuaXphdGlvbjYxMjgxMDc=',
          avatar_url: 'https://avatars.githubusercontent.com/u/6128107?v=4',
          gravatar_id: '',
          url: 'https://api.github.com/users/vuejs',
          html_url: 'https://github.com/vuejs',
          followers_url: 'https://api.github.com/users/vuejs/followers',
          following_url: 'https://api.github.com/users/vuejs/following{/other_user}',
          gists_url: 'https://api.github.com/users/vuejs/gists{/gist_id}',
          starred_url: 'https://api.github.com/users/vuejs/starred{/owner}{/repo}',
          subscriptions_url: 'https://api.github.com/users/vuejs/subscriptions',
          organizations_url: 'https://api.github.com/users/vuejs/orgs',
          repos_url: 'https://api.github.com/users/vuejs/repos',
          events_url: 'https://api.github.com/users/vuejs/events{/privacy}',
          received_events_url: 'https://api.github.com/users/vuejs/received_events',
          type: 'Organization',
          user_view_type: 'public',
          site_admin: false
        },
        html_url: 'https://github.com/vuejs/vue',
        description: 'This is the repo for Vue 2. For Vue 3, go to https://github.com/vuejs/core',
        fork: false,
        url: 'https://api.github.com/repos/vuejs/vue',
        forks_url: 'https://api.github.com/repos/vuejs/vue/forks',
        keys_url: 'https://api.github.com/repos/vuejs/vue/keys{/key_id}',
        collaborators_url: 'https://api.github.com/repos/vuejs/vue/collaborators{/collaborator}',
        teams_url: 'https://api.github.com/repos/vuejs/vue/teams',
        hooks_url: 'https://api.github.com/repos/vuejs/vue/hooks',
        issue_events_url: 'https://api.github.com/repos/vuejs/vue/issues/events{/number}',
        events_url: 'https://api.github.com/repos/vuejs/vue/events',
        assignees_url: 'https://api.github.com/repos/vuejs/vue/assignees{/user}',
        branches_url: 'https://api.github.com/repos/vuejs/vue/branches{/branch}',
        tags_url: 'https://api.github.com/repos/vuejs/vue/tags',
        blobs_url: 'https://api.github.com/repos/vuejs/vue/git/blobs{/sha}',
        git_tags_url: 'https://api.github.com/repos/vuejs/vue/git/tags{/sha}',
        git_refs_url: 'https://api.github.com/repos/vuejs/vue/git/refs{/sha}',
        trees_url: 'https://api.github.com/repos/vuejs/vue/git/trees{/sha}',
        statuses_url: 'https://api.github.com/repos/vuejs/vue/statuses/{sha}',
        languages_url: 'https://api.github.com/repos/vuejs/vue/languages',
        stargazers_url: 'https://api.github.com/repos/vuejs/vue/stargazers',
        contributors_url: 'https://api.github.com/repos/vuejs/vue/contributors',
        subscribers_url: 'https://api.github.com/repos/vuejs/vue/subscribers',
        subscription_url: 'https://api.github.com/repos/vuejs/vue/subscription',
        commits_url: 'https://api.github.com/repos/vuejs/vue/commits{/sha}',
        git_commits_url: 'https://api.github.com/repos/vuejs/vue/git/commits{/sha}',
        comments_url: 'https://api.github.com/repos/vuejs/vue/comments{/number}',
        issue_comment_url: 'https://api.github.com/repos/vuejs/vue/issues/comments{/number}',
        contents_url: 'https://api.github.com/repos/vuejs/vue/contents/{+path}',
        compare_url: 'https://api.github.com/repos/vuejs/vue/compare/{base}...{head}',
        merges_url: 'https://api.github.com/repos/vuejs/vue/merges',
        archive_url: 'https://api.github.com/repos/vuejs/vue/{archive_format}{/ref}',
        downloads_url: 'https://api.github.com/repos/vuejs/vue/downloads',
        issues_url: 'https://api.github.com/repos/vuejs/vue/issues{/number}',
        pulls_url: 'https://api.github.com/repos/vuejs/vue/pulls{/number}',
        milestones_url: 'https://api.github.com/repos/vuejs/vue/milestones{/number}',
        notifications_url: 'https://api.github.com/repos/vuejs/vue/notifications{?since,all,participating}',
        labels_url: 'https://api.github.com/repos/vuejs/vue/labels{/name}',
        releases_url: 'https://api.github.com/repos/vuejs/vue/releases{/id}',
        deployments_url: 'https://api.github.com/repos/vuejs/vue/deployments',
        created_at: '2013-07-29T03:24:51Z',
        updated_at: '2024-10-30T16:11:21Z',
        pushed_at: '2024-10-10T07:24:15Z',
        git_url: 'git://github.com/vuejs/vue.git',
        ssh_url: 'git@github.com:vuejs/vue.git',
        clone_url: 'https://github.com/vuejs/vue.git',
        svn_url: 'https://github.com/vuejs/vue',
        homepage: 'http://v2.vuejs.org',
        size: 32152,
        stargazers_count: 207917,
        watchers_count: 207917,
        language: 'TypeScript',
        has_issues: true,
        has_projects: true,
        has_downloads: true,
        has_wiki: true,
        has_pages: false,
        has_discussions: false,
        forks_count: 33685,
        mirror_url: null,
        archived: false,
        disabled: false,
        open_issues_count: 603,
        license: {
          key: 'mit',
          name: 'MIT License',
          spdx_id: 'MIT',
          url: 'https://api.github.com/licenses/mit',
          node_id: 'MDc6TGljZW5zZTEz'
        },
        allow_forking: true,
        is_template: false,
        web_commit_signoff_required: false,
        topics: [
          'framework',
          'frontend',
          'javascript',
          'vue'
        ],
        visibility: 'public',
        forks: 33685,
        open_issues: 603,
        watchers: 207917,
        default_branch: 'main',
        score: 1
      },
    ],
    totalCount: 2357041
  }

  //изменено name:'react' на name:'react333'
  const editRepository = {
    id: 10270250,
    node_id: 'MDEwOlJlcG9zaXRvcnkxMDI3MDI1MA==',
    name: 'react333',
    full_name: 'facebook/react',
    'private': false,
    owner: {
      login: 'facebook',
      id: 69631,
      node_id: 'MDEyOk9yZ2FuaXphdGlvbjY5NjMx',
      avatar_url: 'https://avatars.githubusercontent.com/u/69631?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/facebook',
      html_url: 'https://github.com/facebook',
      followers_url: 'https://api.github.com/users/facebook/followers',
      following_url: 'https://api.github.com/users/facebook/following{/other_user}',
      gists_url: 'https://api.github.com/users/facebook/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/facebook/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/facebook/subscriptions',
      organizations_url: 'https://api.github.com/users/facebook/orgs',
      repos_url: 'https://api.github.com/users/facebook/repos',
      events_url: 'https://api.github.com/users/facebook/events{/privacy}',
      received_events_url: 'https://api.github.com/users/facebook/received_events',
      type: 'Organization',
      user_view_type: 'public',
      site_admin: false
    },
    html_url: 'https://github.com/facebook/react',
    description: 'The library for web and native user interfaces.',
    fork: false,
    url: 'https://api.github.com/repos/facebook/react',
    forks_url: 'https://api.github.com/repos/facebook/react/forks',
    keys_url: 'https://api.github.com/repos/facebook/react/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/facebook/react/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/facebook/react/teams',
    hooks_url: 'https://api.github.com/repos/facebook/react/hooks',
    issue_events_url: 'https://api.github.com/repos/facebook/react/issues/events{/number}',
    events_url: 'https://api.github.com/repos/facebook/react/events',
    assignees_url: 'https://api.github.com/repos/facebook/react/assignees{/user}',
    branches_url: 'https://api.github.com/repos/facebook/react/branches{/branch}',
    tags_url: 'https://api.github.com/repos/facebook/react/tags',
    blobs_url: 'https://api.github.com/repos/facebook/react/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/facebook/react/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/facebook/react/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/facebook/react/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/facebook/react/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/facebook/react/languages',
    stargazers_url: 'https://api.github.com/repos/facebook/react/stargazers',
    contributors_url: 'https://api.github.com/repos/facebook/react/contributors',
    subscribers_url: 'https://api.github.com/repos/facebook/react/subscribers',
    subscription_url: 'https://api.github.com/repos/facebook/react/subscription',
    commits_url: 'https://api.github.com/repos/facebook/react/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/facebook/react/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/facebook/react/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/facebook/react/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/facebook/react/contents/{+path}',
    compare_url: 'https://api.github.com/repos/facebook/react/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/facebook/react/merges',
    archive_url: 'https://api.github.com/repos/facebook/react/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/facebook/react/downloads',
    issues_url: 'https://api.github.com/repos/facebook/react/issues{/number}',
    pulls_url: 'https://api.github.com/repos/facebook/react/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/facebook/react/milestones{/number}',
    notifications_url: 'https://api.github.com/repos/facebook/react/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/facebook/react/labels{/name}',
    releases_url: 'https://api.github.com/repos/facebook/react/releases{/id}',
    deployments_url: 'https://api.github.com/repos/facebook/react/deployments',
    created_at: '2013-05-24T16:15:54Z',
    updated_at: '2024-10-30T15:55:22Z',
    pushed_at: '2024-10-30T01:51:44Z',
    git_url: 'git://github.com/facebook/react.git',
    ssh_url: 'git@github.com:facebook/react.git',
    clone_url: 'https://github.com/facebook/react.git',
    svn_url: 'https://github.com/facebook/react',
    homepage: 'https://react.dev',
    size: 632802,
    stargazers_count: 228819,
    watchers_count: 228819,
    language: 'JavaScript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: false,
    forks_count: 46825,
    mirror_url: null,
    archived: false,
    disabled: false,
    open_issues_count: 864,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
      node_id: 'MDc6TGljZW5zZTEz'
    },
    allow_forking: true,
    is_template: false,
    web_commit_signoff_required: false,
    topics: [
      'declarative',
      'frontend',
      'javascript',
      'library',
      'react',
      'ui'
    ],
    visibility: 'public',
    forks: 46825,
    open_issues: 864,
    watchers: 228819,
    default_branch: 'main',
    permissions: {
      admin: false,
      maintain: false,
      push: false,
      triage: false,
      pull: true
    },
    score: 1
  }

  test('test removed', () => {
    const test = repositoryReduser(testData, repositoryRemoved({ repositoryId: 28457823 }))
    expect(test.items.length).toBe(2)
  })

  test('test edit', () => {
    const test = repositoryReduser(testData, repositoryEdit({ repository: editRepository }))
    const newName = test.items[1]
    expect(newName.name).toEqual('react333')
  })
})