name: GitHub Pages
run-name: ${{ github.actor }} is rolling out a new version of the app 🚀
on: [push] 
jobs:
  Build-and-Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install npm deps
      working-directory: ./vk-test-app
      run: npm i
    - name: Build app
      working-directory: ./vk-test-app
      run: npm run build
      env:
        VITE_APP_API_KEY: ${{ secrets.GITHUB_TOKEN }}
        VITE_APP_TEST: ${{ secrets.GITHUB_TOKEN }}
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./vk-test-app/dist